version: 2.1 # use CircleCI 2.1

executors:
  node-18-executor:  # Update to a valid Node.js 18 image
    docker:
      - image: circleci/node:18.17.0  # Use a specific version of Node.js 18

commands:
  get_pip:
    description: "Install pip for Python 3"
    steps:
      - run: |
          echo "deb http://archive.debian.org/debian/ stretch main" | sudo tee /etc/apt/sources.list
          echo "deb http://archive.debian.org/debian-security/ stretch/updates main" | sudo tee -a /etc/apt/sources.list
          echo "Acquire::Check-Valid-Until false;" | sudo tee /etc/apt/apt.conf.d/99ignore-valid-until
      - run: sudo apt-get update
      - run: sudo apt-get install python3-dev python3-pip -y
      - run: pip3 install --upgrade pip
  get_aws_cli:
    description: "Install AWS CLI"
    steps:
      - run: sudo pip3 install awscli --upgrade
  install_npm:
    description: "Install the latest npm version"
    steps:
      - run: 'sudo npm install -g npm@latest'
  install_dependencies:
    description: "Install project dependencies"
    steps:
      - run: npm install
  test_code:
    description: "Test the code"
    steps:
      - run: npm test
  test_coverage:
    description: "Check the code coverage"
    steps:
      - run: npm run coverage
  build_project:
    description: "Build the project"
    steps:
      - run: npm run build
  deploy_project:
    description: "Deploy the project"
    steps:
      - run: npm run deploy

jobs:
  build:
    executor: node-18-executor  # Updated executor
    steps:
      - checkout
      - get_pip
      - get_aws_cli
      - install_npm
      - install_dependencies
      - test_code
      - test_coverage
      - build_project
      - deploy_project
